#ifndef __MYUN2_GITHUB__MICRO_MACHINE__BYTE_CODE_H__
#define __MYUN2_GITHUB__MICRO_MACHINE__BYTE_CODE_H__

#define MM_CODE_PUSH	0
#define MM_CODE_POP		1
#define MM_CODE_ADD		2
#define MM_CODE_SUB		3

#define MM_CODE_MUL		8
#define MM_CODE_DIV		9

#define MM_CODE_CMP		32
#define MM_CODE_JMP		40

#define MM_CODE_INPUT	128
#define MM_CODE_OUTPUT	129

#endif//__MYUN2_GITHUB__MICRO_MACHINE__BYTE_CODE_H__
