#ifndef __MYUN2_GITHUB__MICRO_MACHINE__BYTE_CODE_H__
#define __MYUN2_GITHUB__MICRO_MACHINE__BYTE_CODE_H__

#define MM_CODE_PUSH	0
#define MM_CODE_POP		1
#define MM_CODE_INPUT	128
#define MM_CODE_OUTPUT	129

#endif//__MYUN2_GITHUB__MICRO_MACHINE__BYTE_CODE_H__
